"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
require("./globals.css");
const google_1 = require("next/font/google");
const nextjs_1 = require("@clerk/nextjs");
const toaster_provider_1 = require("@/components/providers/toaster-provider");
const confetti_provider_1 = require("@/components/providers/confetti-provider");
const next_1 = require("@vercel/speed-insights/next");
const Providers_1 = require("./Providers");
const localizations_1 = require("@clerk/localizations");
const template_1 = __importDefault(require("./template"));
const inter = (0, google_1.Noto_Kufi_Arabic)({ subsets: ["arabic"] });
exports.metadata = {
    title: "كورسات",
    description: "Generated by create next app",
};
function RootLayout({ children, }) {
    return (<nextjs_1.ClerkProvider localization={localizations_1.arSA}>
      <html lang="en">
        <body className={inter.className}>
          <confetti_provider_1.ConfettiProvider />
          <toaster_provider_1.ToastProvider />
          <Providers_1.Providers>
            <template_1.default>{children}</template_1.default>
          </Providers_1.Providers>
          <next_1.SpeedInsights />
        </body>
      </html>
    </nextjs_1.ClerkProvider>);
}
